version: "3.8"

services:
  yummo-fe:
    depends_on:
      - yummo-be
    links:
      - yummo-be
    restart: always
    image: paravirtualtishu/yummo-fe:latest
    volumes:
      - type: bind
        source: ./fe
        target: /app
    ports:
      - "3000:3000"
    networks:
      - yummo-app

  yummo-be:
    depends_on:
      - postgres-yummo
      - kafka
    links:
      - postgres-yummo
    restart: always
    image: paravirtualtishu/yummo-be:latest
    env_file: global-variables.env
    ports:
      - "6000:8091"
      - "8090:8090"
    networks:
      - yummo-app

  postgres-yummo:
    image: postgres
    container_name: postgres-yummo
    ports:
      - "5432:5432"
    networks:
      - yummo-app
    env_file: global-variables.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-tool:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "9800:80"
    networks:
      - yummo-app
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-yummo

  agent:
    image: portainer/agent:2.13.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - yummo-app

  portainer:
    image: portainer/portainer-ce:2.13.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    networks:
      - yummo-app
    volumes:
      - portainer_data:/data

  nginx:
    ports:
      - "3050:80"
    restart: always
    image: paravirtualtishu/yummo-nginx:latest
    networks:
      - yummo-app
    depends_on:
      - yummo-fe
      - yummo-be
      - db-tool
      - portainer
      - yummo-grafana

  yummo-grafana:
    image: paravirtualtishu/yummo-grafana:latest
    ports:
        - 30000:3000
    restart: always
    depends_on:
        - yummo-be
    networks:
        - yummo-app
    env_file: global-variables.env
    volumes:
      - grafana-storage:/var/lib/grafana

  yummo-mail-service:
    depends_on:
      - yummo-be
      - kafka
    restart: always
    image: paravirtualtishu/yummo-mail-service:latest
    env_file: global-variables.env
    ports:
      - "6060:8080"
      - "8092:8092"
    networks:
      - yummo-app

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    env_file: global-variables.env
    networks:
      - yummo-app

  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "transaction-1:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
        - yummo-app

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - ./srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  yummo-app:
    name: yummo-app

volumes:
  grafana-storage:
  portainer_data:
  postgres_data:
  pgadmin_data:
