apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # - path: /svc1/(.*)
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: gws
      #       port:
      #         number: 80
      - path: /api/(.*)
        pathType: Prefix
        backend:
          service:
            name: yummo-be
            port:
              number: 8091
      - path: /socket/(.*)
        pathType: Prefix
        backend:
          service:
            name: yummo-socket
            port:
              number: 5001
      - path: /yummo-fe/(.*)
        pathType: Prefix
        backend:
          service:
            name: yummo-fe
            port:
              number: 3000
      - path: /nginx-fe/(.*)
        pathType: Prefix
        backend:
          service:
            name: hello
            port:
              number: 80